// Stringhe UI localizzate (IT/EN). La lingua segue il browser/OS, con override
// da Impostazioni → Interfaccia (localStorage 'cockpit-lang': 'it' | 'en' | assente = auto).
const saved = typeof localStorage !== 'undefined' ? localStorage.getItem('cockpit-lang') : null;
export const LANG = saved === 'it' || saved === 'en' ? saved : navigator.language?.toLowerCase().startsWith('it') ? 'it' : 'en';

const IT = {
  you: 'Tu',
  // App — topbar
  costTitle: 'costo · token cumulativi del progetto',
  newChat: 'Nuova chat',
  newChatTitle: 'Chiudi la sessione e riparti da zero',
  history: 'Cronologia',
  historyTitle: 'Sfoglia e riprendi le chat passate del progetto',
  exportChat: 'Esporta',
  exportChatTitle: 'Scarica la conversazione corrente in Markdown',
  ttsTitle: 'Leggi le risposte a voce',
  notifyTitle: 'Notifiche fine-task / permesso',
  terminal: 'Terminale',
  providerTitle: 'Provider della sessione (il cambio riavvia la sessione mantenendo la chat)',
  glmModelTitle: 'Modello del provider GLM (da providers.json / settings z.ai)',
  effortTitle: 'Reasoning effort della sessione',
  sidePanelTitle: 'Pannello todo + stato MCP',
  connected: 'connesso',
  startEngine: 'Avvia engine',
  newSession: 'Nuova sessione',
  // App — errori / notifiche
  tokenNotFound: 'Token non trovato (~/.claude-cockpit/token). Engine mai avviato?',
  engineStartFailed: (err: string) => `Avvio engine fallito: ${err}`,
  taskDone: (project: string) => `Task finito · ${project}`,
  completed: 'completato',
  resultError: (subtype: string) => `errore: ${subtype}`,
  permissionNotify: (project: string) => `Permesso richiesto · ${project}`,
  // App — terminale / layout
  close: 'chiudi',
  resizerTitle: 'Trascina per ridimensionare',
  // Composer
  placeholderWaiting: 'In attesa dell’engine…',
  placeholderBusy: 'Turno in corso — Invio accoda il messaggio, Esc interrompe',
  placeholderIdle: 'Messaggio a Claude — Invio invia, / per i comandi, Ctrl+V incolla screenshot',
  dictateTitle: 'Detta il messaggio',
  send: 'Invia',
  enqueue: 'Accoda',
  stopEsc: 'Stop (Esc)',
  queuedChip: (n: number) => `${n} in coda`,
  // SessionPicker
  minAgo: (n: number) => `${n} min fa`,
  hoursAgo: (n: number) => `${n} h fa`,
  daysAgo: (n: number) => `${n} g fa`,
  catCockpit: 'Cockpit',
  catScheduler: 'Scheduler',
  catTech: 'Tecniche',
  chatHistory: 'Cronologia chat',
  searchPlaceholder: 'Cerca per argomento…',
  inContents: 'nei contenuti',
  inContentsTitle: 'Cerca dentro il contenuto delle conversazioni (Invio)',
  hiddenCount: (n: number) => `${n} nascoste`,
  searching: 'Ricerca in corso…',
  noContentFor: (q: string) => `Nessun contenuto trovato per “${q}”.`,
  noSessions: 'Nessuna sessione (controlla filtri/ricerca).',
  // Tabs
  chat: 'Chat',
  closeTabTitle: 'Chiudi scheda (la conversazione resta in Cronologia)',
  newTabTitle: 'Nuova scheda (sessione parallela)',
  // MdViewer
  copyTextTitle: 'Testo pulito senza sintassi markdown, pronto da incollare',
  copyText: 'copia testo',
  copyMdTitle: 'Sorgente markdown esatto del file',
  copyMd: 'copia md',
  copyPath: 'copia path',
  cannotOpen: (err: string) => `Impossibile aprire il file: ${err}`,
  loading: 'Caricamento…',
  // FileNav
  opFailed: (err: string) => `Operazione fallita: ${err}`,
  useAsProject: 'Usa come progetto',
  removeFromProjects: 'Rimuovi da PROGETTI',
  addToProjects: 'Aggiungi a PROGETTI',
  openTerminalHere: 'Apri terminale qui',
  askClaude: 'Chiedi a Claude',
  newFolderHere: 'Nuova cartella qui',
  newFolderPrompt: 'Nome nuova cartella:',
  openInReader: 'Apri nel lettore',
  revealInExplorer: 'Apri in Esplora Risorse',
  copyPathMenu: 'Copia path',
  copyWinPath: 'Copia path Windows',
  rename: 'Rinomina',
  renamePrompt: 'Nuovo nome:',
  deleteItem: 'Elimina',
  confirmDelete: (name: string, dir: boolean) => `Eliminare ${name}?${dir ? ' (solo se vuota)' : ''}`,
  filesSection: 'FILE',
  loadingLower: 'caricamento…',
  emptyFolder: 'cartella vuota',
  useAsActiveTitle: 'Usa come progetto attivo',
  // ProjectSwitcher
  projectsSection: 'PROGETTI',
  addProject: '+ progetto',
  pathPlaceholder: '/percorso/progetto',
  namePlaceholder: 'nome (opzionale)',
  add: 'Aggiungi',
  cancel: 'Annulla',
  removeFromList: 'Rimuovi dalla lista',
  editProject: 'Modifica icona e nome',
  // McpStatus
  mcpDown: (n: number) => `${n} giù`,
  mcpOk: (n: number) => `${n} ok`,
  refresh: 'Aggiorna',
  // ChatView
  writeToStart: 'Scrivi un messaggio per iniziare.',
  copy: 'copia',
  thinkingBlock: (tok: number) => `ragionamento (${tok} tok ca.)`,
  thinkingChip: (secs: number) => `sta ragionando… ${secs}s`,
  // PermissionPrompt
  permTitle: 'Permesso richiesto:',
  applyEdit: 'Applica modifica',
  allowOnce: 'Consenti una volta',
  allowAlways: 'Consenti sempre',
  editInput: 'Modifica input',
  deny: 'Nega',
  // browser-shim
  tokenPrompt: 'Token engine (~/.claude-cockpit/token):',
  notFromBrowser: 'Non disponibile da browser: avvia l’engine in WSL.',
  // Settings
  settingsTitle: 'Impostazioni',
  settingsBtnTitle: 'Impostazioni (notifiche, Telegram, provider, quick actions…)',
  openOnWindows: 'Apri su Windows',
  winViewTitle: 'claude su Windows nativo (pilota il Chrome di Windows)',
  save: 'Salva',
  saved: 'Salvato ✓',
  secNotify: 'Notifiche',
  notifyDesktop: 'Notifiche desktop a fine task / richiesta permesso',
  notifyPhoneLbl: 'Inoltra anche al telefono via ntfy',
  ntfyTopicLbl: 'Topic ntfy.sh',
  ntfyTopicHint: 'Un nome segreto qualsiasi: iscriviti allo stesso topic nell’app ntfy sul telefono.',
  notifyBrowserOnly: 'Configurabili dall’app desktop (qui nel browser valgono le notifiche del browser).',
  secTelegram: 'Telegram',
  tgActive: 'gateway attivo',
  tgOff: 'gateway spento',
  tgBotToken: 'Bot token (da @BotFather)',
  tgChatId: 'Chat ID autorizzato',
  tgProject: 'Progetto di default (path, vuoto = home)',
  tgSttProvider: 'Provider trascrizione vocali',
  tgSttKey: 'API key trascrizione',
  tgHint: 'Salvando, il bot riparte subito con la nuova configurazione.',
  secProvider: 'Provider alternativi',
  glmConfigDir: 'Config dir (es. ~/.claude-glm)',
  glmModel: 'Modello (es. glm-5.2[1m])',
  glmModels: 'Modelli del selettore (separati da virgola)',
  provName: 'nome provider (es. glm, openrouter)',
  provAdd: 'Aggiungi provider',
  provRemove: 'Rimuovi provider',
  modelSearchPlaceholder: 'cerca modello…',
  modelComboTitle: 'Modello (lista live, cerca per nome)',
  modelLoading: 'carico…',
  modelNoMatch: 'nessun modello',
  provModelsUrl: 'URL catalogo live (opz., stile OpenRouter /models)',
  provModelPrefix: 'Prefisso modelli (opz., es. openrouter,)',
  glmHint: 'Vuoto = switch GLM disabilitato. La config dir è un’installazione Claude Code con le sue credenziali.',
  secQuickActions: 'Quick actions',
  qaLabel: 'Etichetta',
  qaText: 'Prompt / comando',
  qaAdd: '+ aggiungi',
  secEngine: 'Engine',
  allProjectsTitle: 'Cerca in tutti i progetti',
  tabRenameTitle: 'Doppio click per rinominare',
  tabPinTitle: 'Blocca/sblocca in prima posizione',
  qaGlobal: 'globale',
  qaProjectTitle: 'Dove appare questa azione',
  usageAllModels: 'tutti i modelli',
  usageModelCostNote: 'Filtro modello attivo: i costi $ non hanno modello associato e restano esclusi.',
  cfgExport: 'Esporta config',
  cfgExportTitle: 'Scarica un backup dei file config di ~/.claude-cockpit',
  cfgImport: 'Importa config',
  cfgImportTitle: 'Ripristina un backup (sovrascrive i file config presenti)',
  cfgImportBad: 'File non valido: serve un cockpit-config-backup.json.',
  cfgImportDone: (n: number) => `Importati ${n} file. Riapri le impostazioni per vedere i valori aggiornati.`,
  cfgHint: 'Il backup contiene segreti (es. bot Telegram): trattalo come una password. Il token engine NON è incluso (si rigenera da solo).',
  autoCheckpointLbl: 'Checkpoint automatico dei file',
  autoCheckpointHint: 'Snapshot dei file del progetto prima di ogni prompt in vista chat (max uno ogni 10 minuti). Ripristino dal pannello Checkpoint.',
  engineHosts: 'Host in ascolto (uno per riga)',
  engineHostsHint: '127.0.0.1 = solo questo PC. Aggiungi l’IP VPN (es. Tailscale) per usarlo dal telefono.',
  restartRequired: '⚠ Modifica agli host: riavvia l’engine per applicarla.',
  engineInfo: (v: string, home: string) => `Engine v${v} · home ${home}`,
  secUi: 'Interfaccia',
  langLbl: 'Lingua',
  langAuto: 'Auto (browser)',
  langReloadHint: 'La lingua cambia al prossimo ricaricamento della pagina.',
  // MCP add/remove
  mcpAddTitle: 'Connetti un server MCP',
  mcpName: 'Nome',
  mcpTransport: 'Tipo',
  mcpTargetUrl: 'URL del server',
  mcpTargetCmd: 'Comando (es. npx my-mcp-server)',
  mcpHeaders: 'Header (uno per riga, es. Authorization: Bearer …)',
  mcpEnv: 'Variabili env (KEY=VALUE, una per riga)',
  mcpScopeAll: 'tutti i progetti',
  mcpScopeProject: 'questo progetto',
  mcpAdding: 'aggiungo…',
  mcpRemoveTitle: 'Rimuovi server',
  mcpConfirmRemove: 'rimuovere?',
  mcpEmpty: 'Nessun server MCP configurato in Claude Code.',
  mcpRestartNote: 'La sessione si riavvia per caricare la modifica (la chat resta).',
  mcpExport: 'Esporta',
  mcpExportTitle: 'Scarica i server MCP (scope utente) in un file JSON riutilizzabile su un\'altra macchina. Attenzione: il file contiene anche eventuali token.',
  mcpImport: 'Importa',
  mcpImportTitle: 'Importa i server MCP da un file esportato (scope utente).',
  mcpImportBadFile: 'File non valido: serve il JSON esportato da Cockpit (o una mappa {nome: config}).',
  mcpImportDone: (ok: number, err: number) => (err ? `importati ${ok}, falliti ${err}` : `importati ${ok} ✓`),
  // Dettatura
  micNeedsHttps: 'Microfono non disponibile su http: apri il Cockpit dall’app desktop o da un indirizzo https:// (es. tailscale serve — vedi README).',
  micTranscribing: 'Trascrizione in corso…',
  sttLangLbl: 'Lingua dettatura e vocali',
  micDenied: 'Permesso microfono negato: consentilo nelle impostazioni del sito.',
  micError: (code: string) => `Dettatura non riuscita${code ? ` (${code})` : ''}. Riprova.`,
  // Statusline / console / permessi default
  ctxRealTitle: (tot: number, max: number) => `contesto ${tot}k su ${max}k token (dato reale della sessione)`,
  defaultModeLbl: 'Modalità permessi delle nuove sessioni',
  restartCli: 'Riavvia il CLI',
  viewToggleTitle: 'Vista della scheda: CLI nativo di Claude Code o Chat',
  cliModeTitle: 'Modalità permessi del CLI (il cambio rilancia il CLI riprendendo la conversazione)',
  cliNewChat: 'Nuova chat',
  cliNewChatTitle: 'Apre una nuova chat indipendente in una scheda nuova',
  cliHistory: 'Cronologia',
  cliHistoryTitle: 'Riapri una sessione precedente (/resume)',
  // Doctor (verifica prerequisiti)
  inboxOpen: 'Sessioni aperte',
  inboxTitle: 'Sessioni',
  inboxEmpty: 'Nessuna sessione chat avviata in questa finestra.',
  inboxNote: 'Le schede CLI compaiono quando il terminale produce output (euristica: output recente = al lavoro).',
  inboxCliActive: 'CLI attivo',
  inboxStop: 'Interrompi il task di questa sessione',
  inboxPerm: 'In attesa di una decisione permesso: apri la riga per rispondere',
  dropTooBig: (name: string) => `${name}: troppo grande (max 100 kB per i file di testo).`,
  dropUnsupported: (name: string) => `${name}: tipo non supportato (immagini o file di testo).`,
  notifSummary: (cost: string, turns: number, files: string) => `${cost} · ${turns} turni${files ? ` · file: ${files}` : ''}`,
  usageOpen: 'Uso e costi (30 giorni)',
  usageTitle: 'Uso · 30 giorni',
  usageLoading: 'Scansione dei transcript in corso… la prima apertura può richiedere qualche secondo.',
  usageAllProviders: 'tutti i provider',
  usageAllProjects: 'tutti i progetti',
  usageAllOrigins: 'tutte le origini',
  usageTotals: (i: string, c: string, o: string, usd: number) => `Totali: ${i} in · ${c} cache · ${o} out${usd > 0 ? ` · $${usd.toFixed(2)}` : ''}`,
  usageColDate: 'giorno',
  usageCostNote: 'I token sono storici (dai transcript). I costi $ esistono solo da quando l\'engine li registra a fine task — niente stime.',
  sysOpen: 'Sistema · memoria e processi',
  sysTitle: 'Sistema',
  sysLoading: 'Lettura statistiche engine…',
  sysEngineInfo: (v: string, uptime: string) => `Engine v${v} · attivo da ${uptime}`,
  sysMemEngineLabel: 'memoria engine',
  sysMemCgroupLabel: 'memoria cgroup',
  sysMemPeakLabel: 'picco',
  sysColKind: 'tipo',
  sysColProject: 'progetto',
  sysColRss: 'RSS (MB)',
  sysColAge: 'età',
  sysColCmd: 'comando',
  sysKindSdk: 'SDK',
  sysKindPty: 'PTY',
  sysKindMcp: 'MCP',
  sysKindOther: 'ALTRO',
  sysKillTitle: 'Termina processo',
  sysKillConfirm: (pid: number) => `Terminare il processo ${pid} con SIGTERM?`,
  sysKillFailed: (pid: number, err: string) => `Kill del processo ${pid} fallito: ${err}`,
  sysEmpty: 'Nessun processo figlio in esecuzione.',
  cpOpen: 'Checkpoint file del progetto',
  cpTitle: 'Checkpoint',
  cpNote: 'Snapshot dei file del progetto. Il ripristino riporta i file allo stato dello snapshot ma non elimina quelli creati dopo.',
  cpLabelPh: 'etichetta (opzionale)',
  cpCreate: 'Crea checkpoint',
  cpEmpty: 'Nessun checkpoint per questo progetto.',
  cpRestore: 'Ripristina',
  cpConfirm: 'Sicuro?',
  docOpen: 'Verifica sistema',
  docTitle: 'Verifica sistema',
  docConnected: 'engine connesso',
  docDisconnected: 'engine NON connesso',
  docRunning: 'Verifica in corso…',
  docRerun: 'Riprova',
  docStartEngine: 'Avvia engine',
  docLabel: (id: string) =>
    ((({ wsl: 'WSL', wsluser: 'Utente WSL', node: 'Node.js ≥ 20', claude: 'Claude Code CLI', engine: 'Servizio engine', port: 'Porta 8130', update: 'Aggiornamenti' }) as Record<string, string>)[id] ?? id),
  docHintWsl: 'WSL non trovato. In PowerShell (admin): wsl --install, poi riavvia.',
  docHintWslUser: 'Nessuna distro/utente WSL rilevati. Installa Ubuntu: wsl --install -d Ubuntu.',
  docHintNodeWsl: 'Node ≥ 20 manca in WSL. Dentro Ubuntu: sudo apt update && sudo apt install -y nodejs npm (o usa nvm).',
  docHintNode: 'Node ≥ 20 non trovato. Installalo da nodejs.org o con brew install node.',
  docHintClaude: 'Claude Code CLI mancante: npm install -g @anthropic-ai/claude-code, poi lancia claude una volta per il login.',
  docHintEngine: 'Engine non attivo. Dal repo: bash scripts/install-engine-service.sh (WSL/Linux).',
  docHintEngineMac: 'Engine non attivo. Dal repo: bash scripts/install-engine-macos.sh.',
  docHintPort: "L'engine non risponde su 127.0.0.1:8130: avvialo (bottone sotto) o controlla i check precedenti.",
  docHintUpdate: 'Canale aggiornamenti non raggiungibile (github.com): update automatici e avvisi di nuova versione non funzioneranno finché sei offline.',
  docBrowserNote: 'Nel browser i controlli automatici non sono disponibili (usa l\'app desktop). Requisiti della macchina che ospita l\'engine:',
  docReqEngine: 'Engine Cockpit in esecuzione (systemd su Linux/WSL, launchd su macOS) sulla porta 8130',
  docReqClaude: 'Claude Code CLI installato e loggato (comando claude)',
  docReqNode: 'Node.js ≥ 20',
  // Command palette (v0.28)
  cpPlaceholder: 'Cerca o esegui un comando…',
  cpFilterPh: 'Filtra…',
  cpNoResults: 'Nessun risultato',
  cpHintNav: 'naviga',
  cpHintRun: 'esegui',
  cpHintClose: 'chiudi',
  cpOpenTitle: 'Command palette (Ctrl+K)',
  cpSecSession: 'Sessione',
  cpSecGoto: 'Vai a',
  cpSecModel: 'Modello',
  cpSecPanels: 'Pannelli',
  cpSecQuick: 'Azioni rapide',
  cpSecPrefs: 'Preferenze',
  cmdSwitchProject: 'Passa a progetto…',
  cmdProvider: 'Provider…',
  cmdModel: 'Modello…',
  cmdEffort: 'Effort…',
  cmdMode: 'Permessi…',
  cmdToggleView: 'Passa a vista',
  cmdCloseTab: 'Chiudi scheda',
  moreTitle: 'Altro',
  sessionPillTitle: 'Sessione: provider, modello, effort, permessi',
  smTitle: 'Sessione',
  smProvider: 'Provider',
  smModel: 'Modello',
  smEffort: 'Effort',
  smMode: 'Permessi',
};

const EN: typeof IT = {
  you: 'You',
  // App — topbar
  costTitle: 'cost · cumulative project tokens',
  newChat: 'New chat',
  newChatTitle: 'Close the session and start from scratch',
  history: 'History',
  historyTitle: 'Browse and resume past chats of the project',
  exportChat: 'Export',
  exportChatTitle: 'Download the current conversation as Markdown',
  ttsTitle: 'Read responses aloud',
  notifyTitle: 'Task-done / permission notifications',
  terminal: 'Terminal',
  providerTitle: 'Session provider (switching restarts the session keeping the chat)',
  glmModelTitle: 'GLM provider model (from providers.json / z.ai settings)',
  effortTitle: 'Session reasoning effort',
  sidePanelTitle: 'Todo panel + MCP status',
  connected: 'connected',
  startEngine: 'Start engine',
  newSession: 'New session',
  // App — errors / notifications
  tokenNotFound: 'Token not found (~/.claude-cockpit/token). Engine never started?',
  engineStartFailed: (err: string) => `Engine start failed: ${err}`,
  taskDone: (project: string) => `Task finished · ${project}`,
  completed: 'completed',
  resultError: (subtype: string) => `error: ${subtype}`,
  permissionNotify: (project: string) => `Permission requested · ${project}`,
  // App — terminal / layout
  close: 'close',
  resizerTitle: 'Drag to resize',
  // Composer
  placeholderWaiting: 'Waiting for the engine…',
  placeholderBusy: 'Turn in progress — Enter queues the message, Esc interrupts',
  placeholderIdle: 'Message Claude — Enter sends, / for commands, Ctrl+V pastes screenshots',
  dictateTitle: 'Dictate the message',
  send: 'Send',
  enqueue: 'Queue',
  stopEsc: 'Stop (Esc)',
  queuedChip: (n: number) => `${n} queued`,
  // SessionPicker
  minAgo: (n: number) => `${n} min ago`,
  hoursAgo: (n: number) => `${n} h ago`,
  daysAgo: (n: number) => `${n} d ago`,
  catCockpit: 'Cockpit',
  catScheduler: 'Scheduler',
  catTech: 'Technical',
  chatHistory: 'Chat history',
  searchPlaceholder: 'Search by topic…',
  inContents: 'in contents',
  inContentsTitle: 'Search inside conversation contents (Enter)',
  hiddenCount: (n: number) => `${n} hidden`,
  searching: 'Searching…',
  noContentFor: (q: string) => `No content found for “${q}”.`,
  noSessions: 'No sessions (check filters/search).',
  // Tabs
  chat: 'Chat',
  closeTabTitle: 'Close tab (the conversation stays in History)',
  newTabTitle: 'New tab (parallel session)',
  // MdViewer
  copyTextTitle: 'Clean text without markdown syntax, ready to paste',
  copyText: 'copy text',
  copyMdTitle: 'Exact markdown source of the file',
  copyMd: 'copy md',
  copyPath: 'copy path',
  cannotOpen: (err: string) => `Cannot open the file: ${err}`,
  loading: 'Loading…',
  // FileNav
  opFailed: (err: string) => `Operation failed: ${err}`,
  useAsProject: 'Use as project',
  removeFromProjects: 'Remove from PROJECTS',
  addToProjects: 'Add to PROJECTS',
  openTerminalHere: 'Open terminal here',
  askClaude: 'Ask Claude',
  newFolderHere: 'New folder here',
  newFolderPrompt: 'New folder name:',
  openInReader: 'Open in reader',
  revealInExplorer: 'Open in File Explorer',
  copyPathMenu: 'Copy path',
  copyWinPath: 'Copy Windows path',
  rename: 'Rename',
  renamePrompt: 'New name:',
  deleteItem: 'Delete',
  confirmDelete: (name: string, dir: boolean) => `Delete ${name}?${dir ? ' (only if empty)' : ''}`,
  filesSection: 'FILES',
  loadingLower: 'loading…',
  emptyFolder: 'empty folder',
  useAsActiveTitle: 'Use as active project',
  // ProjectSwitcher
  projectsSection: 'PROJECTS',
  addProject: '+ project',
  pathPlaceholder: '/project/path',
  namePlaceholder: 'name (optional)',
  add: 'Add',
  cancel: 'Cancel',
  removeFromList: 'Remove from list',
  editProject: 'Edit icon and name',
  // McpStatus
  mcpDown: (n: number) => `${n} down`,
  mcpOk: (n: number) => `${n} ok`,
  refresh: 'Refresh',
  // ChatView
  writeToStart: 'Write a message to get started.',
  copy: 'copy',
  thinkingBlock: (tok: number) => `reasoning (~${tok} tok)`,
  thinkingChip: (secs: number) => `thinking… ${secs}s`,
  // PermissionPrompt
  permTitle: 'Permission requested:',
  applyEdit: 'Apply change',
  allowOnce: 'Allow once',
  allowAlways: 'Allow always',
  editInput: 'Edit input',
  deny: 'Deny',
  // browser-shim
  tokenPrompt: 'Engine token (~/.claude-cockpit/token):',
  notFromBrowser: 'Not available from browser: start the engine in WSL.',
  // Settings
  settingsTitle: 'Settings',
  settingsBtnTitle: 'Settings (notifications, Telegram, providers, quick actions…)',
  openOnWindows: 'Open on Windows',
  winViewTitle: 'Native Windows claude (drives the Windows Chrome)',
  save: 'Save',
  saved: 'Saved ✓',
  secNotify: 'Notifications',
  notifyDesktop: 'Desktop notifications on task end / permission request',
  notifyPhoneLbl: 'Also forward to phone via ntfy',
  ntfyTopicLbl: 'ntfy.sh topic',
  ntfyTopicHint: 'Any secret name: subscribe to the same topic in the ntfy app on your phone.',
  notifyBrowserOnly: 'Configurable from the desktop app (in the browser, native browser notifications apply).',
  secTelegram: 'Telegram',
  tgActive: 'gateway active',
  tgOff: 'gateway off',
  tgBotToken: 'Bot token (from @BotFather)',
  tgChatId: 'Authorized chat ID',
  tgProject: 'Default project (path, empty = home)',
  tgSttProvider: 'Voice transcription provider',
  tgSttKey: 'Transcription API key',
  tgHint: 'On save, the bot restarts immediately with the new configuration.',
  secProvider: 'Alternative providers',
  glmConfigDir: 'Config dir (e.g. ~/.claude-glm)',
  glmModel: 'Model (e.g. glm-5.2[1m])',
  glmModels: 'Selector models (comma-separated)',
  provName: 'provider name (e.g. glm, openrouter)',
  provAdd: 'Add provider',
  provRemove: 'Remove provider',
  modelSearchPlaceholder: 'search model…',
  modelComboTitle: 'Model (live list, search by name)',
  modelLoading: 'loading…',
  modelNoMatch: 'no models',
  provModelsUrl: 'Live catalog URL (opt., OpenRouter /models style)',
  provModelPrefix: 'Model prefix (opt., e.g. openrouter,)',
  glmHint: 'Empty = GLM switch disabled. The config dir is a Claude Code install with its own credentials.',
  secQuickActions: 'Quick actions',
  qaLabel: 'Label',
  qaText: 'Prompt / command',
  qaAdd: '+ add',
  secEngine: 'Engine',
  allProjectsTitle: 'Search across all projects',
  tabRenameTitle: 'Double-click to rename',
  tabPinTitle: 'Pin/unpin to first position',
  qaGlobal: 'global',
  qaProjectTitle: 'Where this action shows up',
  usageAllModels: 'all models',
  usageModelCostNote: 'Model filter active: recorded $ costs have no model attached and are excluded.',
  cfgExport: 'Export config',
  cfgExportTitle: 'Download a backup of the ~/.claude-cockpit config files',
  cfgImport: 'Import config',
  cfgImportTitle: 'Restore a backup (overwrites existing config files)',
  cfgImportBad: 'Invalid file: expected a cockpit-config-backup.json.',
  cfgImportDone: (n: number) => `Imported ${n} files. Reopen Settings to see the updated values.`,
  cfgHint: 'The backup contains secrets (e.g. Telegram bot): treat it like a password. The engine token is NOT included (it regenerates itself).',
  autoCheckpointLbl: 'Automatic file checkpoints',
  autoCheckpointHint: 'Snapshot the project files before every chat prompt (at most one every 10 minutes). Restore from the Checkpoints panel.',
  engineHosts: 'Listen hosts (one per line)',
  engineHostsHint: '127.0.0.1 = this PC only. Add your VPN IP (e.g. Tailscale) to use it from your phone.',
  restartRequired: '⚠ Hosts changed: restart the engine to apply.',
  engineInfo: (v: string, home: string) => `Engine v${v} · home ${home}`,
  secUi: 'Interface',
  langLbl: 'Language',
  langAuto: 'Auto (browser)',
  langReloadHint: 'The language changes on the next page reload.',
  // MCP add/remove
  mcpAddTitle: 'Connect an MCP server',
  mcpName: 'Name',
  mcpTransport: 'Type',
  mcpTargetUrl: 'Server URL',
  mcpTargetCmd: 'Command (e.g. npx my-mcp-server)',
  mcpHeaders: 'Headers (one per line, e.g. Authorization: Bearer …)',
  mcpEnv: 'Env vars (KEY=VALUE, one per line)',
  mcpScopeAll: 'all projects',
  mcpScopeProject: 'this project',
  mcpAdding: 'adding…',
  mcpRemoveTitle: 'Remove server',
  mcpConfirmRemove: 'remove?',
  mcpEmpty: 'No MCP servers configured in Claude Code.',
  mcpRestartNote: 'The session restarts to load the change (the chat is kept).',
  mcpExport: 'Export',
  mcpExportTitle: 'Download the user-scope MCP servers as a JSON file reusable on another machine. Warning: the file also contains any tokens.',
  mcpImport: 'Import',
  mcpImportTitle: 'Import MCP servers from an exported file (user scope).',
  mcpImportBadFile: 'Invalid file: expected the JSON exported by Cockpit (or a {name: config} map).',
  mcpImportDone: (ok: number, err: number) => (err ? `imported ${ok}, failed ${err}` : `imported ${ok} ✓`),
  // Dictation
  micNeedsHttps: 'Microphone unavailable over http: open Cockpit from the desktop app or an https:// address (e.g. tailscale serve — see README).',
  micTranscribing: 'Transcribing…',
  sttLangLbl: 'Dictation & voice-memo language',
  micDenied: 'Microphone permission denied: allow it in the site settings.',
  micError: (code: string) => `Dictation failed${code ? ` (${code})` : ''}. Try again.`,
  // Statusline / console / default permissions
  ctxRealTitle: (tot: number, max: number) => `context ${tot}k of ${max}k tokens (real session data)`,
  defaultModeLbl: 'Permission mode for new sessions',
  restartCli: 'Restart the CLI',
  viewToggleTitle: 'Tab view: native Claude Code CLI or Chat',
  cliModeTitle: 'CLI permission mode (switching relaunches the CLI resuming the conversation)',
  cliNewChat: 'New chat',
  cliNewChatTitle: 'Open an independent new chat in a new tab',
  cliHistory: 'History',
  cliHistoryTitle: 'Reopen a previous session (/resume)',
  // Doctor (prerequisites check)
  inboxOpen: 'Open sessions',
  inboxTitle: 'Sessions',
  inboxEmpty: 'No chat sessions started in this window.',
  inboxNote: 'CLI tabs appear while the terminal produces output (heuristic: recent output = working).',
  inboxCliActive: 'CLI active',
  inboxStop: 'Interrupt this session\'s task',
  inboxPerm: 'Waiting for a permission decision: open the row to answer',
  dropTooBig: (name: string) => `${name}: too big (text files max 100 kB).`,
  dropUnsupported: (name: string) => `${name}: unsupported type (images or text files).`,
  notifSummary: (cost: string, turns: number, files: string) => `${cost} · ${turns} turns${files ? ` · files: ${files}` : ''}`,
  usageOpen: 'Usage & costs (30 days)',
  usageTitle: 'Usage · 30 days',
  usageLoading: 'Scanning transcripts… the first open can take a few seconds.',
  usageAllProviders: 'all providers',
  usageAllProjects: 'all projects',
  usageAllOrigins: 'all origins',
  usageTotals: (i: string, c: string, o: string, usd: number) => `Totals: ${i} in · ${c} cache · ${o} out${usd > 0 ? ` · $${usd.toFixed(2)}` : ''}`,
  usageColDate: 'day',
  usageCostNote: 'Tokens are historical (from transcripts). Dollar costs only exist since the engine started recording them at task end — no estimates.',
  sysOpen: 'System · memory and processes',
  sysTitle: 'System',
  sysLoading: 'Reading engine stats…',
  sysEngineInfo: (v: string, uptime: string) => `Engine v${v} · up ${uptime}`,
  sysMemEngineLabel: 'engine memory',
  sysMemCgroupLabel: 'cgroup memory',
  sysMemPeakLabel: 'peak',
  sysColKind: 'kind',
  sysColProject: 'project',
  sysColRss: 'RSS (MB)',
  sysColAge: 'age',
  sysColCmd: 'command',
  sysKindSdk: 'SDK',
  sysKindPty: 'PTY',
  sysKindMcp: 'MCP',
  sysKindOther: 'OTHER',
  sysKillTitle: 'Kill process',
  sysKillConfirm: (pid: number) => `Terminate process ${pid} with SIGTERM?`,
  sysKillFailed: (pid: number, err: string) => `Killing process ${pid} failed: ${err}`,
  sysEmpty: 'No child processes running.',
  cpOpen: 'Project file checkpoints',
  cpTitle: 'Checkpoints',
  cpNote: 'Snapshots of the project files. Restoring brings files back to the snapshot state but does not delete files created afterwards.',
  cpLabelPh: 'label (optional)',
  cpCreate: 'Create checkpoint',
  cpEmpty: 'No checkpoints for this project yet.',
  cpRestore: 'Restore',
  cpConfirm: 'Sure?',
  docOpen: 'System check',
  docTitle: 'System check',
  docConnected: 'engine connected',
  docDisconnected: 'engine NOT connected',
  docRunning: 'Checking…',
  docRerun: 'Retry',
  docStartEngine: 'Start engine',
  docLabel: (id: string) =>
    ((({ wsl: 'WSL', wsluser: 'WSL user', node: 'Node.js ≥ 20', claude: 'Claude Code CLI', engine: 'Engine service', port: 'Port 8130', update: 'Updates' }) as Record<string, string>)[id] ?? id),
  docHintWsl: 'WSL not found. In PowerShell (admin): wsl --install, then reboot.',
  docHintWslUser: 'No WSL distro/user detected. Install Ubuntu: wsl --install -d Ubuntu.',
  docHintNodeWsl: 'Node ≥ 20 missing inside WSL. In Ubuntu: sudo apt update && sudo apt install -y nodejs npm (or use nvm).',
  docHintNode: 'Node ≥ 20 not found. Install from nodejs.org or brew install node.',
  docHintClaude: 'Claude Code CLI missing: npm install -g @anthropic-ai/claude-code, then run claude once to log in.',
  docHintEngine: 'Engine not active. From the repo: bash scripts/install-engine-service.sh (WSL/Linux).',
  docHintEngineMac: 'Engine not active. From the repo: bash scripts/install-engine-macos.sh.',
  docHintPort: 'The engine is not answering on 127.0.0.1:8130: start it (button below) or fix the checks above.',
  docHintUpdate: 'Update channel unreachable (github.com): auto-updates and new-version notices will not work while offline.',
  docBrowserNote: 'Automatic checks are not available in the browser (use the desktop app). Requirements on the machine hosting the engine:',
  docReqEngine: 'Cockpit engine running (systemd on Linux/WSL, launchd on macOS) on port 8130',
  docReqClaude: 'Claude Code CLI installed and logged in (claude command)',
  docReqNode: 'Node.js ≥ 20',
  // Command palette (v0.28)
  cpPlaceholder: 'Search or run a command…',
  cpFilterPh: 'Filter…',
  cpNoResults: 'No results',
  cpHintNav: 'navigate',
  cpHintRun: 'run',
  cpHintClose: 'close',
  cpOpenTitle: 'Command palette (Ctrl+K)',
  cpSecSession: 'Session',
  cpSecGoto: 'Go to',
  cpSecModel: 'Model',
  cpSecPanels: 'Panels',
  cpSecQuick: 'Quick actions',
  cpSecPrefs: 'Preferences',
  cmdSwitchProject: 'Switch project…',
  cmdProvider: 'Provider…',
  cmdModel: 'Model…',
  cmdEffort: 'Effort…',
  cmdMode: 'Permissions…',
  cmdToggleView: 'Switch view',
  cmdCloseTab: 'Close tab',
  moreTitle: 'More',
  sessionPillTitle: 'Session: provider, model, effort, permissions',
  smTitle: 'Session',
  smProvider: 'Provider',
  smModel: 'Model',
  smEffort: 'Effort',
  smMode: 'Permissions',
};

export const t = <K extends keyof typeof IT>(k: K): (typeof IT)[K] => (LANG === 'it' ? IT : EN)[k];

export const LOCALE = LANG === 'it' ? 'it-IT' : 'en-US';
