// Stringhe UI localizzate (IT/EN). La lingua segue quella del browser/OS.
export const LANG = navigator.language?.toLowerCase().startsWith('it') ? 'it' : 'en';

const IT = {
  you: 'Tu',
  // App — topbar
  costTitle: 'costo · token cumulativi del progetto',
  ctxTitle: (k: number) => `contesto ~${k}k token (finestra 200k)`,
  newChat: 'Nuova chat',
  newChatTitle: 'Chiudi la sessione e riparti da zero',
  history: 'Cronologia',
  historyTitle: 'Sfoglia e riprendi le chat passate del progetto',
  ttsTitle: 'Leggi le risposte a voce',
  notifyTitle: 'Notifiche fine-task / permesso',
  terminal: 'Terminale',
  providerTitle: 'Provider della sessione (il cambio riavvia la sessione mantenendo la chat)',
  glmModelTitle: 'Modello del provider GLM (da providers.json / settings z.ai)',
  effortTitle: 'Reasoning effort della sessione',
  sidePanelTitle: 'Pannello todo + stato MCP',
  connected: 'connesso',
  startEngine: 'Avvia engine',
  newSession: 'Nuova sessione',
  // App — errori / notifiche
  tokenNotFound: 'Token non trovato (~/.claude-cockpit/token). Engine mai avviato?',
  engineStartFailed: (err: string) => `Avvio engine fallito: ${err}`,
  taskDone: (project: string) => `Task finito · ${project}`,
  completed: 'completato',
  resultError: (subtype: string) => `errore: ${subtype}`,
  permissionNotify: (project: string) => `Permesso richiesto · ${project}`,
  // App — terminale / layout
  close: 'chiudi',
  resizerTitle: 'Trascina per ridimensionare',
  // Composer
  placeholderWaiting: 'In attesa dell’engine…',
  placeholderBusy: 'Turno in corso — Invio accoda il messaggio, Esc interrompe',
  placeholderIdle: 'Messaggio a Claude — Invio invia, / per i comandi, Ctrl+V incolla screenshot',
  dictateTitle: 'Detta il messaggio',
  send: 'Invia',
  enqueue: 'Accoda',
  stopEsc: 'Stop (Esc)',
  queuedChip: (n: number) => `${n} in coda`,
  // SessionPicker
  minAgo: (n: number) => `${n} min fa`,
  hoursAgo: (n: number) => `${n} h fa`,
  daysAgo: (n: number) => `${n} g fa`,
  catCockpit: 'Cockpit',
  catScheduler: 'Scheduler',
  catTech: 'Tecniche',
  chatHistory: 'Cronologia chat',
  searchPlaceholder: 'Cerca per argomento…',
  inContents: 'nei contenuti',
  inContentsTitle: 'Cerca dentro il contenuto delle conversazioni (Invio)',
  hiddenCount: (n: number) => `${n} nascoste`,
  searching: 'Ricerca in corso…',
  noContentFor: (q: string) => `Nessun contenuto trovato per “${q}”.`,
  noSessions: 'Nessuna sessione (controlla filtri/ricerca).',
  // Tabs
  chat: 'Chat',
  closeTabTitle: 'Chiudi scheda (la conversazione resta in Cronologia)',
  newTabTitle: 'Nuova scheda (sessione parallela)',
  // MdViewer
  copyTextTitle: 'Testo pulito senza sintassi markdown, pronto da incollare',
  copyText: 'copia testo',
  copyMdTitle: 'Sorgente markdown esatto del file',
  copyMd: 'copia md',
  copyPath: 'copia path',
  cannotOpen: (err: string) => `Impossibile aprire il file: ${err}`,
  loading: 'Caricamento…',
  // FileNav
  opFailed: (err: string) => `Operazione fallita: ${err}`,
  useAsProject: 'Usa come progetto',
  removeFromProjects: 'Rimuovi da PROGETTI',
  addToProjects: 'Aggiungi a PROGETTI',
  openTerminalHere: 'Apri terminale qui',
  askClaude: 'Chiedi a Claude',
  newFolderHere: 'Nuova cartella qui',
  newFolderPrompt: 'Nome nuova cartella:',
  openInReader: 'Apri nel lettore',
  revealInExplorer: 'Apri in Esplora Risorse',
  copyPathMenu: 'Copia path',
  copyWinPath: 'Copia path Windows',
  rename: 'Rinomina',
  renamePrompt: 'Nuovo nome:',
  deleteItem: 'Elimina',
  confirmDelete: (name: string, dir: boolean) => `Eliminare ${name}?${dir ? ' (solo se vuota)' : ''}`,
  filesSection: 'FILE',
  loadingLower: 'caricamento…',
  emptyFolder: 'cartella vuota',
  useAsActiveTitle: 'Usa come progetto attivo',
  // ProjectSwitcher
  projectsSection: 'PROGETTI',
  addProject: '+ progetto',
  pathPlaceholder: '/percorso/progetto',
  namePlaceholder: 'nome (opzionale)',
  add: 'Aggiungi',
  cancel: 'Annulla',
  removeFromList: 'Rimuovi dalla lista',
  // McpStatus
  mcpDown: (n: number) => `${n} giù`,
  mcpOk: (n: number) => `${n} ok`,
  refresh: 'Aggiorna',
  // ChatView
  writeToStart: 'Scrivi un messaggio per iniziare.',
  copy: 'copia',
  thinkingBlock: (tok: number) => `ragionamento (${tok} tok ca.)`,
  thinkingChip: (secs: number) => `sta ragionando… ${secs}s`,
  // PermissionPrompt
  permTitle: 'Permesso richiesto:',
  applyEdit: 'Applica modifica',
  allowOnce: 'Consenti una volta',
  allowAlways: 'Consenti sempre',
  editInput: 'Modifica input',
  deny: 'Nega',
  // browser-shim
  tokenPrompt: 'Token engine (~/.claude-cockpit/token):',
  notFromBrowser: 'Non disponibile da browser: avvia l’engine in WSL.',
};

const EN: typeof IT = {
  you: 'You',
  // App — topbar
  costTitle: 'cost · cumulative project tokens',
  ctxTitle: (k: number) => `context ~${k}k tokens (200k window)`,
  newChat: 'New chat',
  newChatTitle: 'Close the session and start from scratch',
  history: 'History',
  historyTitle: 'Browse and resume past chats of the project',
  ttsTitle: 'Read responses aloud',
  notifyTitle: 'Task-done / permission notifications',
  terminal: 'Terminal',
  providerTitle: 'Session provider (switching restarts the session keeping the chat)',
  glmModelTitle: 'GLM provider model (from providers.json / z.ai settings)',
  effortTitle: 'Session reasoning effort',
  sidePanelTitle: 'Todo panel + MCP status',
  connected: 'connected',
  startEngine: 'Start engine',
  newSession: 'New session',
  // App — errors / notifications
  tokenNotFound: 'Token not found (~/.claude-cockpit/token). Engine never started?',
  engineStartFailed: (err: string) => `Engine start failed: ${err}`,
  taskDone: (project: string) => `Task finished · ${project}`,
  completed: 'completed',
  resultError: (subtype: string) => `error: ${subtype}`,
  permissionNotify: (project: string) => `Permission requested · ${project}`,
  // App — terminal / layout
  close: 'close',
  resizerTitle: 'Drag to resize',
  // Composer
  placeholderWaiting: 'Waiting for the engine…',
  placeholderBusy: 'Turn in progress — Enter queues the message, Esc interrupts',
  placeholderIdle: 'Message Claude — Enter sends, / for commands, Ctrl+V pastes screenshots',
  dictateTitle: 'Dictate the message',
  send: 'Send',
  enqueue: 'Queue',
  stopEsc: 'Stop (Esc)',
  queuedChip: (n: number) => `${n} queued`,
  // SessionPicker
  minAgo: (n: number) => `${n} min ago`,
  hoursAgo: (n: number) => `${n} h ago`,
  daysAgo: (n: number) => `${n} d ago`,
  catCockpit: 'Cockpit',
  catScheduler: 'Scheduler',
  catTech: 'Technical',
  chatHistory: 'Chat history',
  searchPlaceholder: 'Search by topic…',
  inContents: 'in contents',
  inContentsTitle: 'Search inside conversation contents (Enter)',
  hiddenCount: (n: number) => `${n} hidden`,
  searching: 'Searching…',
  noContentFor: (q: string) => `No content found for “${q}”.`,
  noSessions: 'No sessions (check filters/search).',
  // Tabs
  chat: 'Chat',
  closeTabTitle: 'Close tab (the conversation stays in History)',
  newTabTitle: 'New tab (parallel session)',
  // MdViewer
  copyTextTitle: 'Clean text without markdown syntax, ready to paste',
  copyText: 'copy text',
  copyMdTitle: 'Exact markdown source of the file',
  copyMd: 'copy md',
  copyPath: 'copy path',
  cannotOpen: (err: string) => `Cannot open the file: ${err}`,
  loading: 'Loading…',
  // FileNav
  opFailed: (err: string) => `Operation failed: ${err}`,
  useAsProject: 'Use as project',
  removeFromProjects: 'Remove from PROJECTS',
  addToProjects: 'Add to PROJECTS',
  openTerminalHere: 'Open terminal here',
  askClaude: 'Ask Claude',
  newFolderHere: 'New folder here',
  newFolderPrompt: 'New folder name:',
  openInReader: 'Open in reader',
  revealInExplorer: 'Open in File Explorer',
  copyPathMenu: 'Copy path',
  copyWinPath: 'Copy Windows path',
  rename: 'Rename',
  renamePrompt: 'New name:',
  deleteItem: 'Delete',
  confirmDelete: (name: string, dir: boolean) => `Delete ${name}?${dir ? ' (only if empty)' : ''}`,
  filesSection: 'FILES',
  loadingLower: 'loading…',
  emptyFolder: 'empty folder',
  useAsActiveTitle: 'Use as active project',
  // ProjectSwitcher
  projectsSection: 'PROJECTS',
  addProject: '+ project',
  pathPlaceholder: '/project/path',
  namePlaceholder: 'name (optional)',
  add: 'Add',
  cancel: 'Cancel',
  removeFromList: 'Remove from list',
  // McpStatus
  mcpDown: (n: number) => `${n} down`,
  mcpOk: (n: number) => `${n} ok`,
  refresh: 'Refresh',
  // ChatView
  writeToStart: 'Write a message to get started.',
  copy: 'copy',
  thinkingBlock: (tok: number) => `reasoning (~${tok} tok)`,
  thinkingChip: (secs: number) => `thinking… ${secs}s`,
  // PermissionPrompt
  permTitle: 'Permission requested:',
  applyEdit: 'Apply change',
  allowOnce: 'Allow once',
  allowAlways: 'Allow always',
  editInput: 'Edit input',
  deny: 'Deny',
  // browser-shim
  tokenPrompt: 'Engine token (~/.claude-cockpit/token):',
  notFromBrowser: 'Not available from browser: start the engine in WSL.',
};

export const t = <K extends keyof typeof IT>(k: K): (typeof IT)[K] => (LANG === 'it' ? IT : EN)[k];

export const LOCALE = LANG === 'it' ? 'it-IT' : 'en-US';
