// Stringhe UI localizzate (IT/EN). La lingua segue il browser/OS, con override
// da Impostazioni → Interfaccia (localStorage 'cockpit-lang': 'it' | 'en' | assente = auto).
const saved = typeof localStorage !== 'undefined' ? localStorage.getItem('cockpit-lang') : null;
export const LANG = saved === 'it' || saved === 'en' ? saved : navigator.language?.toLowerCase().startsWith('it') ? 'it' : 'en';

const IT = {
  you: 'Tu',
  // App — topbar
  costTitle: 'costo · token cumulativi del progetto',
  newChat: 'Nuova chat',
  newChatTitle: 'Chiudi la sessione e riparti da zero',
  history: 'Cronologia',
  historyTitle: 'Sfoglia e riprendi le chat passate del progetto',
  ttsTitle: 'Leggi le risposte a voce',
  notifyTitle: 'Notifiche fine-task / permesso',
  terminal: 'Terminale',
  providerTitle: 'Provider della sessione (il cambio riavvia la sessione mantenendo la chat)',
  glmModelTitle: 'Modello del provider GLM (da providers.json / settings z.ai)',
  effortTitle: 'Reasoning effort della sessione',
  sidePanelTitle: 'Pannello todo + stato MCP',
  connected: 'connesso',
  startEngine: 'Avvia engine',
  newSession: 'Nuova sessione',
  // App — errori / notifiche
  tokenNotFound: 'Token non trovato (~/.claude-cockpit/token). Engine mai avviato?',
  engineStartFailed: (err: string) => `Avvio engine fallito: ${err}`,
  taskDone: (project: string) => `Task finito · ${project}`,
  completed: 'completato',
  resultError: (subtype: string) => `errore: ${subtype}`,
  permissionNotify: (project: string) => `Permesso richiesto · ${project}`,
  // App — terminale / layout
  close: 'chiudi',
  resizerTitle: 'Trascina per ridimensionare',
  // Composer
  placeholderWaiting: 'In attesa dell’engine…',
  placeholderBusy: 'Turno in corso — Invio accoda il messaggio, Esc interrompe',
  placeholderIdle: 'Messaggio a Claude — Invio invia, / per i comandi, Ctrl+V incolla screenshot',
  dictateTitle: 'Detta il messaggio',
  send: 'Invia',
  enqueue: 'Accoda',
  stopEsc: 'Stop (Esc)',
  queuedChip: (n: number) => `${n} in coda`,
  // SessionPicker
  minAgo: (n: number) => `${n} min fa`,
  hoursAgo: (n: number) => `${n} h fa`,
  daysAgo: (n: number) => `${n} g fa`,
  catCockpit: 'Cockpit',
  catScheduler: 'Scheduler',
  catTech: 'Tecniche',
  chatHistory: 'Cronologia chat',
  searchPlaceholder: 'Cerca per argomento…',
  inContents: 'nei contenuti',
  inContentsTitle: 'Cerca dentro il contenuto delle conversazioni (Invio)',
  hiddenCount: (n: number) => `${n} nascoste`,
  searching: 'Ricerca in corso…',
  noContentFor: (q: string) => `Nessun contenuto trovato per “${q}”.`,
  noSessions: 'Nessuna sessione (controlla filtri/ricerca).',
  // Tabs
  chat: 'Chat',
  closeTabTitle: 'Chiudi scheda (la conversazione resta in Cronologia)',
  newTabTitle: 'Nuova scheda (sessione parallela)',
  // MdViewer
  copyTextTitle: 'Testo pulito senza sintassi markdown, pronto da incollare',
  copyText: 'copia testo',
  copyMdTitle: 'Sorgente markdown esatto del file',
  copyMd: 'copia md',
  copyPath: 'copia path',
  cannotOpen: (err: string) => `Impossibile aprire il file: ${err}`,
  loading: 'Caricamento…',
  // FileNav
  opFailed: (err: string) => `Operazione fallita: ${err}`,
  useAsProject: 'Usa come progetto',
  removeFromProjects: 'Rimuovi da PROGETTI',
  addToProjects: 'Aggiungi a PROGETTI',
  openTerminalHere: 'Apri terminale qui',
  askClaude: 'Chiedi a Claude',
  newFolderHere: 'Nuova cartella qui',
  newFolderPrompt: 'Nome nuova cartella:',
  openInReader: 'Apri nel lettore',
  revealInExplorer: 'Apri in Esplora Risorse',
  copyPathMenu: 'Copia path',
  copyWinPath: 'Copia path Windows',
  rename: 'Rinomina',
  renamePrompt: 'Nuovo nome:',
  deleteItem: 'Elimina',
  confirmDelete: (name: string, dir: boolean) => `Eliminare ${name}?${dir ? ' (solo se vuota)' : ''}`,
  filesSection: 'FILE',
  loadingLower: 'caricamento…',
  emptyFolder: 'cartella vuota',
  useAsActiveTitle: 'Usa come progetto attivo',
  // ProjectSwitcher
  projectsSection: 'PROGETTI',
  addProject: '+ progetto',
  pathPlaceholder: '/percorso/progetto',
  namePlaceholder: 'nome (opzionale)',
  add: 'Aggiungi',
  cancel: 'Annulla',
  removeFromList: 'Rimuovi dalla lista',
  // McpStatus
  mcpDown: (n: number) => `${n} giù`,
  mcpOk: (n: number) => `${n} ok`,
  refresh: 'Aggiorna',
  // ChatView
  writeToStart: 'Scrivi un messaggio per iniziare.',
  copy: 'copia',
  thinkingBlock: (tok: number) => `ragionamento (${tok} tok ca.)`,
  thinkingChip: (secs: number) => `sta ragionando… ${secs}s`,
  // PermissionPrompt
  permTitle: 'Permesso richiesto:',
  applyEdit: 'Applica modifica',
  allowOnce: 'Consenti una volta',
  allowAlways: 'Consenti sempre',
  editInput: 'Modifica input',
  deny: 'Nega',
  // browser-shim
  tokenPrompt: 'Token engine (~/.claude-cockpit/token):',
  notFromBrowser: 'Non disponibile da browser: avvia l’engine in WSL.',
  // Settings
  settingsTitle: 'Impostazioni',
  settingsBtnTitle: 'Impostazioni (notifiche, Telegram, provider, quick actions…)',
  save: 'Salva',
  saved: 'Salvato ✓',
  secNotify: 'Notifiche',
  notifyDesktop: 'Notifiche desktop a fine task / richiesta permesso',
  notifyPhoneLbl: 'Inoltra anche al telefono via ntfy',
  ntfyTopicLbl: 'Topic ntfy.sh',
  ntfyTopicHint: 'Un nome segreto qualsiasi: iscriviti allo stesso topic nell’app ntfy sul telefono.',
  notifyBrowserOnly: 'Configurabili dall’app desktop (qui nel browser valgono le notifiche del browser).',
  secTelegram: 'Telegram',
  tgActive: 'gateway attivo',
  tgOff: 'gateway spento',
  tgBotToken: 'Bot token (da @BotFather)',
  tgChatId: 'Chat ID autorizzato',
  tgProject: 'Progetto di default (path, vuoto = home)',
  tgSttProvider: 'Provider trascrizione vocali',
  tgSttKey: 'API key trascrizione',
  tgHint: 'Salvando, il bot riparte subito con la nuova configurazione.',
  secProvider: 'Provider alternativo (GLM)',
  glmConfigDir: 'Config dir (es. ~/.claude-glm)',
  glmModel: 'Modello (es. glm-5.2)',
  glmHint: 'Vuoto = switch GLM disabilitato. La config dir è un’installazione Claude Code con le sue credenziali.',
  secQuickActions: 'Quick actions',
  qaLabel: 'Etichetta',
  qaText: 'Prompt / comando',
  qaAdd: '+ aggiungi',
  secEngine: 'Engine',
  engineHosts: 'Host in ascolto (uno per riga)',
  engineHostsHint: '127.0.0.1 = solo questo PC. Aggiungi l’IP VPN (es. Tailscale) per usarlo dal telefono.',
  restartRequired: '⚠ Modifica agli host: riavvia l’engine per applicarla.',
  engineInfo: (v: string, home: string) => `Engine v${v} · home ${home}`,
  secUi: 'Interfaccia',
  langLbl: 'Lingua',
  langAuto: 'Auto (browser)',
  langReloadHint: 'La lingua cambia al prossimo ricaricamento della pagina.',
  // MCP add/remove
  mcpAddTitle: 'Connetti un server MCP',
  mcpName: 'Nome',
  mcpTransport: 'Tipo',
  mcpTargetUrl: 'URL del server',
  mcpTargetCmd: 'Comando (es. npx my-mcp-server)',
  mcpHeaders: 'Header (uno per riga, es. Authorization: Bearer …)',
  mcpEnv: 'Variabili env (KEY=VALUE, una per riga)',
  mcpScopeAll: 'tutti i progetti',
  mcpScopeProject: 'questo progetto',
  mcpAdding: 'aggiungo…',
  mcpRemoveTitle: 'Rimuovi server',
  mcpConfirmRemove: 'rimuovere?',
  mcpEmpty: 'Nessun server MCP configurato in Claude Code.',
  mcpRestartNote: 'La sessione si riavvia per caricare la modifica (la chat resta).',
  // Dettatura
  micNeedsHttps: 'Microfono non disponibile su http: apri il Cockpit dall’app desktop o da un indirizzo https:// (es. tailscale serve — vedi README).',
  micTranscribing: 'Trascrizione in corso…',
  micDenied: 'Permesso microfono negato: consentilo nelle impostazioni del sito.',
  micError: (code: string) => `Dettatura non riuscita${code ? ` (${code})` : ''}. Riprova.`,
  // Statusline / console / permessi default
  ctxRealTitle: (tot: number, max: number) => `contesto ${tot}k su ${max}k token (dato reale della sessione)`,
  defaultModeLbl: 'Modalità permessi delle nuove sessioni',
  restartCli: 'Riavvia il CLI',
  viewToggleTitle: 'Vista della scheda: CLI nativo di Claude Code o Chat',
};

const EN: typeof IT = {
  you: 'You',
  // App — topbar
  costTitle: 'cost · cumulative project tokens',
  newChat: 'New chat',
  newChatTitle: 'Close the session and start from scratch',
  history: 'History',
  historyTitle: 'Browse and resume past chats of the project',
  ttsTitle: 'Read responses aloud',
  notifyTitle: 'Task-done / permission notifications',
  terminal: 'Terminal',
  providerTitle: 'Session provider (switching restarts the session keeping the chat)',
  glmModelTitle: 'GLM provider model (from providers.json / z.ai settings)',
  effortTitle: 'Session reasoning effort',
  sidePanelTitle: 'Todo panel + MCP status',
  connected: 'connected',
  startEngine: 'Start engine',
  newSession: 'New session',
  // App — errors / notifications
  tokenNotFound: 'Token not found (~/.claude-cockpit/token). Engine never started?',
  engineStartFailed: (err: string) => `Engine start failed: ${err}`,
  taskDone: (project: string) => `Task finished · ${project}`,
  completed: 'completed',
  resultError: (subtype: string) => `error: ${subtype}`,
  permissionNotify: (project: string) => `Permission requested · ${project}`,
  // App — terminal / layout
  close: 'close',
  resizerTitle: 'Drag to resize',
  // Composer
  placeholderWaiting: 'Waiting for the engine…',
  placeholderBusy: 'Turn in progress — Enter queues the message, Esc interrupts',
  placeholderIdle: 'Message Claude — Enter sends, / for commands, Ctrl+V pastes screenshots',
  dictateTitle: 'Dictate the message',
  send: 'Send',
  enqueue: 'Queue',
  stopEsc: 'Stop (Esc)',
  queuedChip: (n: number) => `${n} queued`,
  // SessionPicker
  minAgo: (n: number) => `${n} min ago`,
  hoursAgo: (n: number) => `${n} h ago`,
  daysAgo: (n: number) => `${n} d ago`,
  catCockpit: 'Cockpit',
  catScheduler: 'Scheduler',
  catTech: 'Technical',
  chatHistory: 'Chat history',
  searchPlaceholder: 'Search by topic…',
  inContents: 'in contents',
  inContentsTitle: 'Search inside conversation contents (Enter)',
  hiddenCount: (n: number) => `${n} hidden`,
  searching: 'Searching…',
  noContentFor: (q: string) => `No content found for “${q}”.`,
  noSessions: 'No sessions (check filters/search).',
  // Tabs
  chat: 'Chat',
  closeTabTitle: 'Close tab (the conversation stays in History)',
  newTabTitle: 'New tab (parallel session)',
  // MdViewer
  copyTextTitle: 'Clean text without markdown syntax, ready to paste',
  copyText: 'copy text',
  copyMdTitle: 'Exact markdown source of the file',
  copyMd: 'copy md',
  copyPath: 'copy path',
  cannotOpen: (err: string) => `Cannot open the file: ${err}`,
  loading: 'Loading…',
  // FileNav
  opFailed: (err: string) => `Operation failed: ${err}`,
  useAsProject: 'Use as project',
  removeFromProjects: 'Remove from PROJECTS',
  addToProjects: 'Add to PROJECTS',
  openTerminalHere: 'Open terminal here',
  askClaude: 'Ask Claude',
  newFolderHere: 'New folder here',
  newFolderPrompt: 'New folder name:',
  openInReader: 'Open in reader',
  revealInExplorer: 'Open in File Explorer',
  copyPathMenu: 'Copy path',
  copyWinPath: 'Copy Windows path',
  rename: 'Rename',
  renamePrompt: 'New name:',
  deleteItem: 'Delete',
  confirmDelete: (name: string, dir: boolean) => `Delete ${name}?${dir ? ' (only if empty)' : ''}`,
  filesSection: 'FILES',
  loadingLower: 'loading…',
  emptyFolder: 'empty folder',
  useAsActiveTitle: 'Use as active project',
  // ProjectSwitcher
  projectsSection: 'PROJECTS',
  addProject: '+ project',
  pathPlaceholder: '/project/path',
  namePlaceholder: 'name (optional)',
  add: 'Add',
  cancel: 'Cancel',
  removeFromList: 'Remove from list',
  // McpStatus
  mcpDown: (n: number) => `${n} down`,
  mcpOk: (n: number) => `${n} ok`,
  refresh: 'Refresh',
  // ChatView
  writeToStart: 'Write a message to get started.',
  copy: 'copy',
  thinkingBlock: (tok: number) => `reasoning (~${tok} tok)`,
  thinkingChip: (secs: number) => `thinking… ${secs}s`,
  // PermissionPrompt
  permTitle: 'Permission requested:',
  applyEdit: 'Apply change',
  allowOnce: 'Allow once',
  allowAlways: 'Allow always',
  editInput: 'Edit input',
  deny: 'Deny',
  // browser-shim
  tokenPrompt: 'Engine token (~/.claude-cockpit/token):',
  notFromBrowser: 'Not available from browser: start the engine in WSL.',
  // Settings
  settingsTitle: 'Settings',
  settingsBtnTitle: 'Settings (notifications, Telegram, providers, quick actions…)',
  save: 'Save',
  saved: 'Saved ✓',
  secNotify: 'Notifications',
  notifyDesktop: 'Desktop notifications on task end / permission request',
  notifyPhoneLbl: 'Also forward to phone via ntfy',
  ntfyTopicLbl: 'ntfy.sh topic',
  ntfyTopicHint: 'Any secret name: subscribe to the same topic in the ntfy app on your phone.',
  notifyBrowserOnly: 'Configurable from the desktop app (in the browser, native browser notifications apply).',
  secTelegram: 'Telegram',
  tgActive: 'gateway active',
  tgOff: 'gateway off',
  tgBotToken: 'Bot token (from @BotFather)',
  tgChatId: 'Authorized chat ID',
  tgProject: 'Default project (path, empty = home)',
  tgSttProvider: 'Voice transcription provider',
  tgSttKey: 'Transcription API key',
  tgHint: 'On save, the bot restarts immediately with the new configuration.',
  secProvider: 'Alternative provider (GLM)',
  glmConfigDir: 'Config dir (e.g. ~/.claude-glm)',
  glmModel: 'Model (e.g. glm-5.2)',
  glmHint: 'Empty = GLM switch disabled. The config dir is a Claude Code install with its own credentials.',
  secQuickActions: 'Quick actions',
  qaLabel: 'Label',
  qaText: 'Prompt / command',
  qaAdd: '+ add',
  secEngine: 'Engine',
  engineHosts: 'Listen hosts (one per line)',
  engineHostsHint: '127.0.0.1 = this PC only. Add your VPN IP (e.g. Tailscale) to use it from your phone.',
  restartRequired: '⚠ Hosts changed: restart the engine to apply.',
  engineInfo: (v: string, home: string) => `Engine v${v} · home ${home}`,
  secUi: 'Interface',
  langLbl: 'Language',
  langAuto: 'Auto (browser)',
  langReloadHint: 'The language changes on the next page reload.',
  // MCP add/remove
  mcpAddTitle: 'Connect an MCP server',
  mcpName: 'Name',
  mcpTransport: 'Type',
  mcpTargetUrl: 'Server URL',
  mcpTargetCmd: 'Command (e.g. npx my-mcp-server)',
  mcpHeaders: 'Headers (one per line, e.g. Authorization: Bearer …)',
  mcpEnv: 'Env vars (KEY=VALUE, one per line)',
  mcpScopeAll: 'all projects',
  mcpScopeProject: 'this project',
  mcpAdding: 'adding…',
  mcpRemoveTitle: 'Remove server',
  mcpConfirmRemove: 'remove?',
  mcpEmpty: 'No MCP servers configured in Claude Code.',
  mcpRestartNote: 'The session restarts to load the change (the chat is kept).',
  // Dictation
  micNeedsHttps: 'Microphone unavailable over http: open Cockpit from the desktop app or an https:// address (e.g. tailscale serve — see README).',
  micTranscribing: 'Transcribing…',
  micDenied: 'Microphone permission denied: allow it in the site settings.',
  micError: (code: string) => `Dictation failed${code ? ` (${code})` : ''}. Try again.`,
  // Statusline / console / default permissions
  ctxRealTitle: (tot: number, max: number) => `context ${tot}k of ${max}k tokens (real session data)`,
  defaultModeLbl: 'Permission mode for new sessions',
  restartCli: 'Restart the CLI',
  viewToggleTitle: 'Tab view: native Claude Code CLI or Chat',
};

export const t = <K extends keyof typeof IT>(k: K): (typeof IT)[K] => (LANG === 'it' ? IT : EN)[k];

export const LOCALE = LANG === 'it' ? 'it-IT' : 'en-US';
